//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

//TODO: update namespace, as required
namespace CreateManifestFilter
{

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//TODO: Set IsNullable=true
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class filters {
    
    private filtersFilter[] filterField;
    
    private uint majorVersionField;
    
    private uint minorVersionField;
    
    public filters() {
        this.majorVersionField = ((uint)(0));
        this.minorVersionField = ((uint)(1));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("filter")]
    public filtersFilter[] filter {
        get {
            return this.filterField;
        }
        set {
            this.filterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint majorVersion {
        get {
            return this.majorVersionField;
        }
        set {
            this.majorVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint minorVersion {
        get {
            return this.minorVersionField;
        }
        set {
            this.minorVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class filtersFilter {
    
    private filtersFilterAbsTimeInHNS absTimeInHNSField;
    
    private string[] textField;
    
    private string nameField;
    
    /// <remarks/>
    public filtersFilterAbsTimeInHNS absTimeInHNS {
        get {
            return this.absTimeInHNSField;
        }
        set {
            this.absTimeInHNSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class filtersFilterAbsTimeInHNS {
    
    private ulong geField;
    
    private bool geFieldSpecified;
    
    private ulong leField;
    
    private bool leFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ge {
        get {
            return this.geField;
        }
        set {
            this.geField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool geSpecified {
        get {
            return this.geFieldSpecified;
        }
        set {
            this.geFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong le {
        get {
            return this.leField;
        }
        set {
            this.leField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool leSpecified {
        get {
            return this.leFieldSpecified;
        }
        set {
            this.leFieldSpecified = value;
        }
    }
  }
}
